globals:
  labels: &labels
    time:
      - "Time: <1 Hour"
      - "Time: <2 Hours"
      - "Time: <4 Hours"
      - "Time: <1 Day"
      - "Time: <1 Week"
    priority:
      - "Priority: 1 (Normal)"
      - "Priority: 2 (Medium)"
      - "Priority: 3 (High)"
      - "Priority: 4 (Urgent)"
      - "Priority: 5 (Emergency)"

plugins:
  issues.closed:
    - uses:
        - plugin: ubiquity-whilefoo/comment-incentives-2:compute.yml@interface-with-kernel
          type: github
          with:
            evmNetworkId: 100
            isNftRewardEnabled: true
            evmPrivateEncrypted: ytOIGj-ECNFVu7c2PjeE08nySalxdHklTPbrPp5pJmIrcsSEOnCLhTO5xIfGdMDcKj28EUd3K43CB6KJYPNHHyHQTZAYpjvd-pgpWSG6PEsyYQ_OMYPDY-aLFbkM4JgN7rQB_SBDp4iUFqgrRfW8RA
  issue_comment.created:
    - name: "Run on commment created"
      uses:
        - id: plugin-A
          plugin: https://ubiquibot-command-query-user.vipline-dev.workers.dev

    - name: "Assistive Pricing"
      command: "/labels"
      uses:
        - type: github
          plugin: ubiquibot-whilefoo-testing/assistive-pricing@assistive-pricing
          with:
            labels: *labels

  issues.labeled:
    - name: "Assistive Pricing"
      uses:
        - type: github
          plugin: ubiquibot-whilefoo-testing/assistive-pricing@assistive-pricing
          with:
            labels: *labels
  issues.unlabeled:
    - name: "Assistive Pricing"
      uses:
        - type: github
          plugin: ubiquibot-whilefoo-testing/assistive-pricing@assistive-pricing
          with:
            labels: *labels
  label.edited:
    - name: "Assistive Pricing"
      uses:
        - type: github
          plugin: ubiquibot-whilefoo-testing/assistive-pricing@assistive-pricing
          with:
            labels: *labels

