handlers:
  commands: {}
  events:
    issues.closed:
      - workflow:
          owner: ubiquity-whilefoo
          repository: comment-incentives-2
          workflowId: compute.yml
          ref: interface-with-kernel
