
plugins:
  issues.closed:
    - uses:
        - plugin: ubiquity-whilefoo/comment-incentives-2:compute.yml@interface-with-kernel
          type: github
          with:
            evmNetworkId: 100
            isNftRewardEnabled: true
            evmPrivateEncrypted: ytOIGj-ECNFVu7c2PjeE08nySalxdHklTPbrPp5pJmIrcsSEOnCLhTO5xIfGdMDcKj28EUd3K43CB6KJYPNHHyHQTZAYpjvd-pgpWSG6PEsyYQ_OMYPDY-aLFbkM4JgN7rQB_SBDp4iUFqgrRfW8RA
  issue_comment.created:
    - name: "Run on commment created"
      uses:
        - id: plugin-A
          type: github
          plugin: ubiquibot-whilefoo-testing/plugin-A
          with:
            test-input: plugin-A
        - plugin: ubiquibot-whilefoo-testing/plugin-B
          type: github
          with:
            test-input: ${{ plugin-A.output.test_output }}

